<?php
$usuarios = [
  [
    "id" => "user_001",
    "nombre" => "Soledad",
    "apellido" => "Bazzana",
    "edad" => 32,
    "sexo" => "F",
    "email" => "solbazzana@hotmail.com",
    "imagen" => "./img/users/user_001.jpg",
    "fechaIngreso" => "13/02/2019",
    "compras" => ["almo_003", "banq_002"],
  ],
  [
    "id" => "user_002",
    "nombre" => "Victoria",
    "apellido" => "Arnoldi",
    "edad" => 32,
    "sexo" => "F",
    "email" => "victoriaarnoldi@gmail.com",
    "imagen" => "./img/users/user_002.jpg",
    "fechaIngreso" => "17/03/2019",
    "compras" => ["alfo_002", "banq_001", "puff_001"],
  ],
  [
    "id" => "user_003",
    "nombre" => "Gonzalo",
    "apellido" => "García Costoya",
    "edad" => 32,
    "sexo" => "M",
    "email" => "gcostoya02@gmail.com",
    "imagen" => "./img/users/user_003.jpg",
    "fechaIngreso" => "22/04/2019",
    "compras" => ["bols_001"],
  ],
];

$articulos = [
  [
    "id" => "almo_001",
    "categoria" => "Almohadones",
    "subCategoria" => "Tusor Liso",
    "titulo" => "Almohadón Nórdico 40x40",
    "descripcion" => "Almohadón de pelo de zorro sintético importado. Lavable apto para lavarropas.",
    "imagen" => "./img/articles/almo_001.jpg",
    "fechaIngreso" => "20/04/2019",
    "medidas" => "40x40x20",
    "cantidad" => 10,
    "precio" => 610,
    "cuotas" => 6,
    "descuento" => 20,
  ],
  [
    "id" => "almo_002",
    "categoria" => "Almohadones",
    "subCategoria" => "Estampados",
    "titulo" => "Almohadón Estampado 50*50",
    "descripcion" => "Almohadón Estampado Blanco y Negro. Relleno Vellón Siliconado.",
    "imagen" => "./img/articles/almo_002.jpg",
    "fechaIngreso" => "21/04/2019",
    "medidas" => "50x50x20",
    "cantidad" => 10,
    "precio" => 410,
    "cuotas" => 12,
    "descuento" => 0,
  ],
  [
    "id" => "almo_003",
    "categoria" => "Almohadones",
    "subCategoria" => "Tusor Pintado A Manos",
    "titulo" => "Almohadón Libertad 40x40",
    "descripcion" => "Almohadón tusor crudo pintado a mano - Rosa y Dorado- 40x40",
    "imagen" => "./img/articles/almo_003.jpg",
    "fechaIngreso" => "22/04/2019",
    "medidas" => "40x40x20",
    "cantidad" => 6,
    "precio" => 450,
    "cuotas" => 6,
    "descuento" => 0,
  ],
  [
    "id" => "banq_001",
    "categoria" => "Muebles",
    "subCategoria" => "Bancos",
    "titulo" => "Banquito Nórdico Con funda Pelo",
    "descripcion" => "Banco Mini con funda desmontable de pelo sintético lavable.",
    "imagen" => "./img/articles/banq_001.jpg",
    "fechaIngreso" => "20/04/2019",
    "medidas" => "60x30x30",
    "cantidad" => 8,
    "precio" => 590,
    "cuotas" => 12,
    "descuento" => 5,
  ],
  [
    "id" => "banq_002",
    "categoria" => "Muebles",
    "subCategoria" => "Sillones",
    "titulo" => "Sillón De Mimbre 2 Cuerpos",
    "descripcion" => "Sillón De Mimbre 2 Cuerpos",
    "imagen" => "./img/articles/banq_002.jpg",
    "fechaIngreso" => "20/04/2019",
    "medidas" => "120x150x80",
    "cantidad" => 4,
    "precio" => 1600,
    "cuotas" => 12,
    "descuento" => 13,
  ],
  [
    "id" => "alfo_001",
    "categoria" => "Alfombras",
    "subCategoria" => "Lino",
    "titulo" => "Alfombra de Lino 100x100",
    "descripcion" => "Alfombra de lino acolchada, 1 mt de diámetro",
    "imagen" => "./img/articles/alfo_001.jpg",
    "fechaIngreso" => "20/04/2019",
    "medidas" => "100x100x10",
    "cantidad" => 6,
    "precio" => 1300,
    "cuotas" => 3,
    "descuento" => 0,
  ],
  [
    "id" => "alfo_002",
    "categoria" => "Alfombras",
    "subCategoria" => "Play Mats",
    "titulo" => "Play mat 130x130",
    "descripcion" => "Play mat, 1.3 mts de diámetro",
    "imagen" => "./img/articles/alfo_002.jpg",
    "fechaIngreso" => "21/04/2019",
    "medidas" => "130x130x10",
    "cantidad" => 6,
    "precio" => 1200,
    "cuotas" => 10,
    "descuento" => 10,
  ],
  [
    "id" => "puff_001",
    "categoria" => "Puffs",
    "subCategoria" => "Grandes",
    "titulo" => "Puff Grande",
    "descripcion" => "Puff pelo largo sintético.",
    "imagen" => "./img/articles/puff_001.jpg",
    "fechaIngreso" => "26/04/2019",
    "medidas" => "120x80x80",
    "cantidad" => 8,
    "precio" => 1900,
    "cuotas" => 12,
    "descuento" => 30,
  ],
  [
    "id" => "puff_002",
    "categoria" => "Puffs",
    "subCategoria" => "Pequeños",
    "titulo" => "Puff Pequeño",
    "descripcion" => "Puff pelo largo sintético.",
    "imagen" => "./img/articles/puff_002.jpg",
    "fechaIngreso" => "25/04/2019",
    "medidas" => "90x50x50",
    "cantidad" => 8,
    "precio" => 1500,
    "cuotas" => 12,
    "descuento" => 25,
  ],
  [
    "id" => "bols_001",
    "categoria" => "Bolsas De Dormir",
    "subCategoria" => "Grandes",
    "titulo" => "Bolsa de dormir",
    "descripcion" => "Bolsa de dormir super abrigadita de castorino.",
    "imagen" => "./img/articles/bols_001.jpg",
    "fechaIngreso" => "25/04/2019",
    "medidas" => "120x60x20",
    "cantidad" => 8,
    "precio" => 2500,
    "cuotas" => 10,
    "descuento" => 14,
  ],
];

?>
